version: '3.7'
services:
    ppi-db:
        image: postgres:${DB_VERSION}
        container_name: ppi-db
        restart: always
        ports:
            - 5432:5432
        environment:
            - PPI_USER=${DB_USER}
            - PPI_DB=${DB_NAME}
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=${DB_PASSWORD} # Will be used for `postgres` & `ppi_data` users
            - PGPASSWORD=${DB_PASSWORD}
        networks:
            - default
        volumes:
            - ./conf/postgres/initdb:/docker-entrypoint-initdb.d
            - pgdata:/var/lib/postgresql/data

    ppi-parseymcparseface:
        image: andersrye/parsey-mcparseface-server
        contain_name: ppi-parseymcparseface
        ports:
            - 7777:80
        networks:
            - default

networks:
  default:

volumes:
    pgdata:
